In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.3.0


In [3]:
tfvar = tf.Variable([7,10])

In [4]:
tfvar

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

In [5]:
tfconst = tf.constant([10,7])

In [6]:
tfconst

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [7]:
tfvar[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 10])>

In [8]:
random_1 = tf.random.Generator.from_seed(42)

In [9]:
random_1 = random_1.normal(shape=(3,2))

In [10]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))

In [12]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [13]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [14]:
random_1,random_2,random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

#### shuffle a tensor

In [15]:
not_shuffled = tf.constant([[2,3],[4,6],[7,9]])

In [16]:
not_shuffled.ndim

2

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 6],
       [7, 9]])>

In [18]:
tf.random.set_seed(42) #This will keep the random order constant. but tf.random.shuffle(not_shuffled, seed=42) will not work
tf.random.shuffle(not_shuffled) #Every time we run it we get different order. But seed=something also gives different order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 9],
       [2, 3]])>

In [19]:
### Numpy Array to tensors using tf.constant

numpy_A = np.arange(1,25,dtype=np.int32)

In [20]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

##### converting a numpy array to tensors

In [21]:
numpy_A = tf.constant(numpy_A)

In [22]:
numpy_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

#### changing the shape from 1D to 2D

In [23]:
numpy_A = tf.constant(numpy_A, shape=(2,3,4))

In [24]:
numpy_A.ndim

3

In [25]:
tf.size(numpy_A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

#### Numpy Array and tensors are almost same but tensors work fast in gpu

#### adding new dimension

In [26]:
rank_2_tensor = tf.constant([[2,3],[5,6]])

In [27]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

#### Adding an extra dimension

In [28]:
rank_4_tensor = rank_2_tensor[:,:,tf.newaxis]

In [29]:
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[5],
        [6]]])>

#### Another way of Adding extra Tensor

In [30]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[5],
        [6]]])>

In [31]:
rank_3_tensor.ndim

3

#### Alternative to tf.newaxis

In [32]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [5, 6]]])>

In [33]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[5, 6]]])>

In [34]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[5],
        [6]]])>

## Manipulating Tensors(Tensor operations) +,-,*,/

In [35]:
tensor = tf.constant([[6,7],[5,2]])

#### Adding a scalar to tensor

In [36]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 17],
       [15, 12]])>

In [37]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 70],
       [50, 20]])>

In [38]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 0, -3]])>

In [39]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3. , 3.5],
       [2.5, 1. ]])>

### We can also use tensorflow built-in functions

In [40]:
tf.multiply(tensor,10) #This will be fast in GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 70],
       [50, 20]])>

#### Original tensor is unchanged

In [41]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [5, 2]])>

### matrix Multiplication

In [42]:
tensor1 = tf.constant([[4,1],[9,7]])

In [43]:
tf.matmul(tensor,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[87, 55],
       [38, 19]])>

#### multiplying Directly two matrices. This multiplies element wise

In [44]:
tensor * tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24,  7],
       [45, 14]])>

## Python uses "@" to multiply matrix

In [45]:
tensor@tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[87, 55],
       [38, 19]])>

#### create a tensor of 3,2

In [46]:
X = tf.constant([[1,2],[4,3],[7,9]])

In [47]:
Y = tf.constant([[2,7,8],[6,3,8]])

In [48]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 3],
        [7, 9]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 7, 8],
        [6, 3, 8]])>)

In [49]:
X@Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  13,  24],
       [ 26,  37,  56],
       [ 68,  76, 128]])>

#### Matrix multiplication are dot products

### To reshpe any matrix use tf.reshape(X, shape(3,2))

### Also we can use tf.reshape(X, shape=(2,3)).shape, Y.shape

In [50]:
tf.reshape(X, shape=(3,2)).shape, Y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [51]:
tf.matmul(tf.reshape(X,shape=(3,2)),Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  13,  24],
       [ 26,  37,  56],
       [ 68,  76, 128]])>

In [52]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 3],
        [7, 9]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 7, 8],
        [6, 3, 8]])>)

#### Transpose of a matrix

In [53]:
X = tf.transpose(X)

In [54]:
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 3, 9]])>

In [55]:
Y = tf.transpose(Y)

In [56]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 6],
       [7, 3],
       [8, 8]])>

In [57]:
X@Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[86, 74],
       [97, 93]])>

#### For multiplication we can also use tf.tensordot()

In [58]:
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[86, 74],
       [97, 93]])>

### Default datatype is int32. How to change to float32

In [59]:
B = tf.constant([1.5,2.3])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 2.3], dtype=float32)>

#### How to get memory any element occupies in python

In [60]:
import sys
sys.getsizeof(B)

168

### Change from float32 to float16 ## Modern operators can run faster. tensors will take less space.

In [61]:
D = tf.cast(B, dtype=tf.float16)

In [62]:
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 2.3], dtype=float16)>

In [63]:
import sys
sys.getsizeof(D)

168

#### getting absolute values

In [64]:
D = tf.constant([-9,-8])

In [65]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 8])>

#### Find mean of a tensor in tensorflow

##### Create a Random Tensor with values between 0 and 100 using numpy random array.

In [66]:
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([28, 63, 85,  3, 25, 73, 60, 75, 86, 35, 83,  5,  2,  0, 78, 93, 95,
       38, 58,  8, 72, 66, 86, 88,  3, 71, 82,  7,  8, 76, 64, 30, 53, 12,
       20, 47, 27, 64, 56, 54, 60, 61, 64, 78, 44, 94, 17, 14, 47, 51])>

In [67]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [68]:
tf.reduce_min(E) ## Also we can use np.min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [69]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [70]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [71]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2509>

### calculating variance and standard deviation.Inport tensorflow_probability.

In [72]:
import tensorflow_probability as tfp

In [73]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=855>

In [74]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=855.5876>

In [76]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

##### get maximum value within those element and its location

In [77]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

#### Index of our largest value function

In [80]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

##### Find the max value of F

In [81]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

#### Check for equality

In [83]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

##### Find the positional minimum

In [84]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

#### find the minimum using the positional minimum index

In [85]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#### Squeezing a tensor (removing all single dimensions)

In [87]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [88]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One hot encoding

#### create a list of indices

In [89]:
some_list = [0,1,2,3]

### One hot encode our list of indices

In [91]:
tf.one_hot(some_list)

TypeError: one_hot() missing 1 required positional argument: 'depth'

In [93]:
tf.one_hot(some_list,4) # You have to give the depth of 4 as there are 4 elements

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [94]:
tf.one_hot(some_list,depth=4, on_value="yoyo", off_value="honeysingh")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yoyo', b'honeysingh', b'honeysingh', b'honeysingh'],
       [b'honeysingh', b'yoyo', b'honeysingh', b'honeysingh'],
       [b'honeysingh', b'honeysingh', b'yoyo', b'honeysingh'],
       [b'honeysingh', b'honeysingh', b'honeysingh', b'yoyo']],
      dtype=object)>

### New way to create tensor

In [95]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

#### Square it

In [96]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [97]:
tf.reshape(H, shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

#### SQRT will not work with this problem because it does not work with int32 but float, double etc

In [99]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [100]:
tf.log(tf.cast(H, dtype=tf.float32))

AttributeError: module 'tensorflow' has no attribute 'log'

In [101]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Create a tensor with numpy array

In [102]:
J = tf.constant(np.array([2,3,4,5]))
J

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

#### Convert tensorflow into numpy array

In [103]:
np.array(J), type(np.array(J))

(array([2, 3, 4, 5]), numpy.ndarray)

In [104]:
J.numpy(), type(J.numpy()) # Can also use this to convert

(array([2, 3, 4, 5]), numpy.ndarray)