In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
lst1 = [1,2,3,4,5]
lst2 = [5,6,7,8,9]
lst3 = [4,6,7,9,1]

In [7]:
arr = np.array([lst1,lst2,lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 6, 7, 9, 1]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 4, 6, 7, 9, 1]])

In [12]:
arr.shape

(3, 5)

In [14]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [17]:
arr1 = arr[:,3:]

In [18]:
arr1.shape

(3, 2)

In [19]:
arr=np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr=np.arange(0,10,step=2)

In [22]:
arr

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [24]:
arr/2

array([0., 1., 2., 3., 4.])

In [25]:
arr%2

array([0, 0, 0, 0, 0], dtype=int32)

In [26]:
arr%3

array([0, 2, 1, 0, 2], dtype=int32)

In [27]:
arr<2

array([ True, False, False, False, False])

In [29]:
arr[arr<5]

array([0, 2, 4])

In [32]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [33]:
np.random.rand(3,3)

array([[0.37091467, 0.71198117, 0.6963367 ],
       [0.20375687, 0.58506343, 0.42453077],
       [0.28697826, 0.5285345 , 0.02425487]])

In [35]:
np.random.randn(3,3)

array([[ 0.46703437, -0.21185391,  2.76488002],
       [ 0.23076792,  0.97580258,  0.41134566],
       [ 1.27374349,  0.16196848, -0.7299544 ]])

In [37]:
np.random.randint(0,100,8)

array([23, 27, 95, 59, 61, 14, 35, 71])

In [40]:
np.random.random_sample((1,5))

array([[0.39557402, 0.36726229, 0.75886225, 0.41712636, 0.86384107]])