In [201]:
listsample = [1,2,2,3,4,5,6,7]
listsample

[1, 2, 2, 3, 4, 5, 6, 7]

In [202]:
lst=[1,2,'ff','ttt']
lst

[1, 2, 'ff', 'ttt']

In [203]:
from array import *

### make an integer array

In [204]:
arrsample = array('i',[3,2,3,4])
arrsample

array('i', [3, 2, 3, 4])

In [205]:
for x in arrsample:
    print(x)

3
2
3
4


In [206]:
tupleex = ('sss',9,8,'data')
tupleex

('sss', 9, 8, 'data')

In [207]:
dictsam = {'key1':5,'hjjj':'key2'}
dictsam

{'key1': 5, 'hjjj': 'key2'}

In [208]:
dictsam['hjjj']

'key2'

### using list as an element

In [209]:
dictsam1 = ([('first',1),('second',2),('four',4)])

In [210]:
dictsam1

[('first', 1), ('second', 2), ('four', 4)]

### Set Sample

In [211]:
setex = {'sett',0,'hhhh',99}
setex

{0, 99, 'hhhh', 'sett'}

In [212]:
strsample = "learning"

In [213]:
strsample[-2]

'n'

In [214]:
strsample.index('ning')

4

### range indexing

In [215]:
rangesample = range(0,12,4)
rangesample

range(0, 12, 4)

In [216]:
for i in rangesample: print(i)

0
4
8


In [217]:
rangesample.index(8)

2

### slicing data. String is "learning"

In [218]:
strsample[slice(1,4,1)]

'ear'

In [219]:
strsample[slice(1,7,2)]

'eri'

In [220]:
strsample[:]

'learning'

In [221]:
strsample[:3] # starts slicing from beginning just before 3rd element

'lea'

### concatenation

In [222]:
print(strsample+" ","python")

learning  python


In [223]:
print(strsample)

learning


In [224]:
newstring = strsample+" ","python"

In [225]:
print(newstring)

('learning ', 'python')


In [226]:
print(listsample+["py"]) # listsample+"py" . This will give error as "py" is just string. Use square bracket for list.

[1, 2, 2, 3, 4, 5, 6, 7, 'py']


In [227]:
arrsample+array("i",[50,60]) # you cannot use a list here

array('i', [3, 2, 3, 4, 50, 60])

### adding elements to tuple

In [228]:
tupleex+(50,60)

('sss', 9, 8, 'data', 50, 60)

In [229]:
print(strsample)

learning


In [230]:
tupleex

('sss', 9, 8, 'data')

In [231]:
tupleex[2:]*2

(8, 'data', 8, 'data')

###### fgdfgd

In [232]:
sample=array('d',[2.2,2,5,6]) 

In [233]:
sample

array('d', [2.2, 2.0, 5.0, 6.0])

### using Format for multiple substituion and value formatting

In [234]:
name1="Amit"
name2="Ayush"
name3="Akshit"

### {} are called Placeholders

In [235]:
name='{} {}. {}.'.format(name1, name2, name3)

In [236]:
print(name)

Amit Ayush. Akshit.


In [237]:
print(dir(name))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [238]:
print(help(str))

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [239]:
print(help(str.find))

Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.

None


### update method

In [240]:
setex.update([5,10])

In [241]:
print(setex)

{0, 99, 5, 10, 'hhhh', 'sett'}


In [242]:
print(dictsam)

{'key1': 5, 'hjjj': 'key2'}


In [243]:
dictsam["key3"] = 5

In [244]:
print(dictsam)

{'key1': 5, 'hjjj': 'key2', 'key3': 5}


In [245]:
dictsam.update(key3=9) # Reassigning a value to a key in a dictionary

In [246]:
dictsam.get("key3")

9

### Return all keys in the dictionary

In [247]:
dictsam.keys()

dict_keys(['key1', 'hjjj', 'key3'])

In [248]:
dictsam.items()

dict_items([('key1', 5), ('hjjj', 'key2'), ('key3', 9)])

### insert() method

In [249]:
print(arrsample)

array('i', [3, 2, 3, 4])


In [250]:
arrsample.insert(1,100)

In [251]:
print(arrsample)

array('i', [3, 100, 2, 3, 4])


In [252]:
print(listsample)

[1, 2, 2, 3, 4, 5, 6, 7]


In [253]:
listsample.insert(5,24)

In [254]:
print(listsample)

[1, 2, 2, 3, 4, 24, 5, 6, 7]


### using pop() to delete elements using its index

In [258]:
arrsample.pop() #this even prints the deleted element. As no parameter wwas given it deleted the last data

3

In [263]:
arrsample[2]

2

In [264]:
listsample.pop(3)

4

In [265]:
listsample

[1, 2, 2, 24, 5, 6, 7]

In [266]:
dictsam

{'key1': 5, 'hjjj': 'key2', 'key3': 9}

In [267]:
dictsam.pop('hjjj')

'key2'

In [268]:
dictsam

{'key1': 5, 'key3': 9}

### using remove() to remove an item

In [269]:
arrsample

array('i', [3, 100, 2])

In [272]:
arrsample.remove(2)

In [273]:
arrsample

array('i', [3, 100])

In [275]:
listsample

[1, 2, 2, 24, 5, 6, 7]

In [276]:
listsample.remove(7)

In [277]:
listsample

[1, 2, 2, 24, 5, 6]

### Using del operation

In [278]:
del setex

In [279]:
setex

NameError: name 'setex' is not defined

In [280]:
del listsample[2:4]

In [281]:
listsample

[1, 2, 5, 6]

### extending method used to add the specified list elements to the end of current list

In [282]:
arrsample

array('i', [3, 100])

In [285]:
arrsample.extend((5,6,8))

In [286]:
arrsample

array('i', [3, 100, 5, 6, 8])

In [287]:
arrsample.extend(("sam"))

TypeError: an integer is required (got type str)

In [291]:
arrsample.fromlist([3,4]) #using from list to add a list of elements to an array

In [290]:
arrsample

array('i', [3, 100, 5, 6, 8, 3, 4])

### SET will have only unique data

In [292]:
A = {1,2,3,5,2,6,2,54,5,65,5}
print(A)

{1, 2, 3, 65, 5, 6, 54}


In [293]:
B = {2,5,7,8}

In [294]:
print(A|B) This gives the union data

{1, 2, 3, 65, 5, 6, 7, 8, 54}


In [296]:
print(A.union(B))

{1, 2, 3, 65, 5, 6, 7, 8, 54}


In [297]:
print(A & B) # Checking union of two sets

{2, 5}


In [298]:
print(A.intersection(B))

{2, 5}


# NUMPY

In [299]:
import numpy as np

In [320]:
listsample = [1,2,3,3,3,4,5,6,7]

In [321]:
lst = np.array(listsample, dtype=int)

In [322]:
lst

array([1, 2, 3, 3, 3, 4, 5, 6, 7])

In [323]:
print(type(lst))

<class 'numpy.ndarray'>


In [324]:
print(len(lst))

9


In [325]:
print(lst.ndim)
print(lst.shape)

1
(9,)


In [326]:
print(lst.reshape(3,3))

[[1 2 3]
 [3 3 4]
 [5 6 7]]


### reshape will arrange the elements into new dimensions

In [327]:
print(lst.reshape(3,-1)) # -1 will automatically decides how many columns will be there.

[[1 2 3]
 [3 3 4]
 [5 6 7]]


In [329]:
print(lst.ndim)

1


In [330]:
my_list1 = [1,2,3,4,5]
my_list2 = [5,6,3,2,1]
my_list3 = [7,9,5,2,1]

newlist = np.array(my_list1,my_list2,my_list3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [331]:
newlist = np.array([my_list1,my_list2,my_list3]) # This is the Correct Usage is 

In [332]:
print(newlist)

[[1 2 3 4 5]
 [5 6 3 2 1]
 [7 9 5 2 1]]


In [334]:
print(newlist.ndim)

2


In [340]:
print(newlist.reshape(3,-1))

[[1 2 3 4 5]
 [5 6 3 2 1]
 [7 9 5 2 1]]


In [341]:
newlist.shape

(3, 5)

### ARANGE Function

In [343]:
mynewlist = np.arange(24) # start value by default is 0. It will start from 0 and print till 23

In [345]:
print(mynewlist)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [349]:
mynewlist1 = np.arange(5,24,2) #starts from 5 with increment 2 steps and ends before 24

In [350]:
print(mynewlist1)

[ 5  7  9 11 13 15 17 19 21 23]


## reshaping the array reshape(no of divisions of array, num of rows, no of columns)

In [351]:
mynewlist1.reshape(5,2,1)

array([[[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]],

       [[21],
        [23]]])

# Arithmetic of Arrays

In [364]:
arr1 = np.array([1,2,3,4,5]) 

In [365]:
arr2 = np.array([11,12,13,14,15])

In [366]:
print(arr1+arr2) # Add did not add the array

[12 14 16 18 20]


In [367]:
print(np.add(arr1,arr2)) # Remember this should be numpy array not python array

[12 14 16 18 20]


In [368]:
print(np.subtract(arr1,arr2))

[-10 -10 -10 -10 -10]


In [369]:
print(arr1*arr2)

[11 24 39 56 75]


In [370]:
print(np.multiply(arr1,arr2))

[11 24 39 56 75]


In [373]:
print(arr1.dot(arr2))
print(np.dot(arr1,arr2))

205
205


In [374]:
print(arr1/arr2)
print(np.divide(arr1,arr2))

[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]


In [375]:
print(np.sum(arr1))

15


### using axis=0 represents performing operation on each column and axis=1 represenets performing operations on each row

In [377]:
print(np.sum(arr2,axis=0))

65


In [381]:
print(np.sum(arrsample,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1